-- AlterTable
ALTER TABLE "Booking" ADD COLUMN "infantCarrierCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Booking" ADD COLUMN "childSeatCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Booking" ADD COLUMN "boosterCount" INTEGER NOT NULL DEFAULT 0;
